### PR TITLE
Fix truncStringToPlotWidth to allow vector input

### LINKED ISSUE #38: Obscure qQCReport error
Dear QuasR team,

Please see below for the obscure error that qQCReport threw:
Screenshot 2023-06-02 at 20 57 42

The PDF was still generated, it just stopped after the mapping rate barplots.

For reference, here is what is returned by the qProject object:
Screenshot 2023-06-02 at 21 00 32
Screenshot 2023-06-02 at 21 00 40
Screenshot 2023-06-02 at 21 00 47

It is possible that the error is generated by the terrible FASTQ filenames, though as shown by the partial PDF, it was not an issue for previous plots.

If needed, FMI developers can find the qProject object in this file:
`/tungstenfs/scratch/ggrossha/smitalex/RProjects/methstep/modENCODE_L3_histone_marks/RDATA/proj.RData`

And the partial QC PDF here:
`/tungstenfs/scratch/ggrossha/smitalex/RProjects/methstep/modENCODE_L3_histone_marks/OUTPUT/qc_report.pdf`

Thank you for your time and help!

Best regards,

-- Alex

### PR DESCRIPTION
**Pull request by csoneson**
Closes #38

### CODE REVIEW

**Comment by skiaphrene** [comment]
As far as I can tell, I managed to install and load the PR development version of QuasR. The error is now different, and I assume it's related:
Screenshot 2023-06-05 at 11 11 26
(I assume I do not need to redo the entire mapping of the qProject?)
Thanks for looking into this Charlotte!

**Comment by csoneson** [comment]
@skiaphrene I think this is actually a different issue (unrelated to the length of the file names, rather related to the large number of files). I think I have fixed this - could you try again?

**Comment by skiaphrene** [comment]
I just tried again and saw no change in the error message. Would you like me to send you the qProject object?

**Comment by csoneson** [comment]
I can't test it with your object since I don't have permission to read the FASTQ/BAM files. But just extracting and running the code that creates the mapping plot works for me (and running this code with the previous version gives me the error you see above). Did you restart the session after installing the new version, to make sure you are using the right version?

**Comment by skiaphrene** [comment]
You are right, it works now. Must have installed the new version but it must not have loaded over the previous. Sorry, and thank you!

-- Alex S.

Adam Alexander T. SMITH
Bioinformatician for the Biological clocks and timers in development Group
[Image]
Friedrich Miescher Institute for Biomedical Research
Maulbeerstrasse 66 - 4058 Basel - Switzerland
www.fmi.ch<http://www.fmi.ch/>

From: Charlotte Soneson ***@***.***>
Date: Tuesday, 6 June 2023 at 16:35
To: fmicompbio/QuasR ***@***.***>
Cc: Smith, Adam Alexander Thil ***@***.***>, Mention ***@***.***>
Subject: Re: [fmicompbio/QuasR] Fix truncStringToPlotWidth to allow vector input (PR #39)

I can't test it with your object since I don't have permission to read the FASTQ/BAM files. But just extracting and running the code that creates the mapping plot works for me (and running this code with the previous version gives me the error you see above). Did you restart the session after installing the new version, to make sure you are using the right version?

**Review by mbstadler — APPROVED** [review]
Thank you @csoneson and @skiaphrene , I am merging the fix now and will also port it to `RELEASE_3_17`

**Pull request merged**
